#!/usr/bin/env bash

listPackages() {
  find . -name '*.proto' ! -path './vendor/*' ! -path './tmp/*' -print0 | xargs -0 -n1 dirname | sort | uniq
}

mkdir -p generated/swift

for pkg in $(listPackages); do
  protoc \
    --swift_out=generated/swift \
    --swift_opt=Visibility=Public \
    -I ./protos \
    $(ls -1 ${pkg}/*.proto)  

  protoc \
    --grpc-swift_out=generated/swift \
    --grpc-swift_opt=Visibility=Public \
    -I ./protos \
    $(ls -1 ${pkg}/*.proto)
done
